version: '3.2'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - backend
    ports:
      - 1883:1883

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - backend
    volumes:
      - ./custom.ini:/etc/grafana/grafana.ini

networks:
  backend:
    driver: bridge
    